parameters:
    # Blogger contact email address
    boxenmieten_app.emails.contact_email: boxenmieten@gmail.com
    
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: BoxenmietenAppBundle:Menu:customMenu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default