PaLogic\Bundle_app_homepage:
    pattern:  /
    defaults: { _controller: PaLogic\BundleAppBundle:Page:index }
    requirements:
        _method:  GET
        
PaLogic\Bundle_app_me:
    pattern:  /me
    defaults: { _controller: PaLogic\BundleAppBundle:Page:me }
    requirements:
        _method:  GET
        
PaLogic\Bundle_app_info:
    pattern:  /infos
    defaults: { _controller: PaLogic\BundleAppBundle:Page:info }
    requirements:
        _method:  GET
        
PaLogic\Bundle_app_contact:
    pattern:  /kontakt
    defaults: { _controller: PaLogic\BundleAppBundle:Page:contact }
    requirements:
        _method:  GET|POST
        
PaLogic\Bundle_app_image_show:
    pattern:  /bild/{id}/{slug}
    defaults: { _controller: PaLogic\BundleAppBundle:Image:show }
    requirements:
        _method:  GET
        id: \d+
        
PaLogic\Bundle_app_sets:
    pattern:  /angebote
    defaults: { _controller: PaLogic\BundleAppBundle:Set:index }
    requirements:
        _method:  GET
        
PaLogic\Bundle_app_components:
    pattern:  /komponente
    defaults: { _controller: PaLogic\BundleAppBundle:Component:index }
    requirements:
        _method:  GET
        
PaLogic\Bundle_app_set_show:
    pattern:  /angebote/{id}/{slug}
    defaults: { _controller: PaLogic\BundleAppBundle:Set:show }
    requirements:
        _method:  GET
        id: \d+
        
PaLogic\Bundle_app_component_show:
    pattern:  /komponente/{id}/{slug}
    defaults: { _controller: PaLogic\BundleAppBundle:Component:show }
    requirements:
        _method:  GET
        id: \d+