boxenmieten_app_homepage:
    pattern:  /
    defaults: { _controller: BoxenmietenAppBundle:Page:index }
    requirements:
        _method:  GET
        
boxenmieten_app_me:
    pattern:  /me
    defaults: { _controller: BoxenmietenAppBundle:Page:me }
    requirements:
        _method:  GET
        
boxenmieten_app_info:
    pattern:  /infos
    defaults: { _controller: BoxenmietenAppBundle:Page:info }
    requirements:
        _method:  GET
        
boxenmieten_app_contact:
    pattern:  /kontakt
    defaults: { _controller: BoxenmietenAppBundle:Page:contact }
    requirements:
        _method:  GET|POST
        
boxenmieten_app_set_categories:
    pattern:  /musikanlagen
    defaults: { _controller: BoxenmietenAppBundle:SetCategory:index }
    requirements:
        _method:  GET
        
boxenmieten_app_articles:
    pattern:  /artikel
    defaults: { _controller: BoxenmietenAppBundle:Article:index }
    requirements:
        _method:  GET
        
boxenmieten_app_set_show:
    pattern:  /set/{id}/{slug}
    defaults: { _controller: BoxenmietenAppBundle:Set:show }
    requirements:
        _method:  GET
        id: \d+

boxenmieten_app_set_category_show:
    pattern:  /musikanlagen/{id}/{slug}
    defaults: { _controller: BoxenmietenAppBundle:SetCategory:show }
    requirements:
        _method:  GET
        id: \d+

boxenmieten_app_article_show:
    pattern:  /artikel/{id}/{slug}
    defaults: { _controller: BoxenmietenAppBundle:Article:show }
    requirements:
        _method:  GET
        id: \d+

boxenmieten_app_component_show:
    pattern:  /komponente/{id}/{slug}
    defaults: { _controller: BoxenmietenAppBundle:Component:show }
    requirements:
        _method:  GET
        id: \d+
