boxenmieten_app_homepage:
    pattern:  /
    defaults: { _controller: BoxenmietenAppBundle:Page:index }
    requirements:
        _method:  GET
        
boxenmieten_app_me:
    pattern:  /me
    defaults: { _controller: BoxenmietenAppBundle:Page:me }
    requirements:
        _method:  GET
        
boxenmieten_app_info:
    pattern:  /infos
    defaults: { _controller: BoxenmietenAppBundle:Page:info }
    requirements:
        _method:  GET
        
boxenmieten_app_contact:
    pattern:  /kontakt
    defaults: { _controller: BoxenmietenAppBundle:Page:contact }
    requirements:
        _method:  GET|POST
        
boxenmieten_app_sets:
    pattern:  /angebote
    defaults: { _controller: BoxenmietenAppBundle:Set:index }
    requirements:
        _method:  GET
        
boxenmieten_app_components:
    pattern:  /komponente
    defaults: { _controller: BoxenmietenAppBundle:Component:index }
    requirements:
        _method:  GET
        
boxenmieten_app_set_show:
    pattern:  /angebote/{id}/{slug}
    defaults: { _controller: BoxenmietenAppBundle:Set:show }
    requirements:
        _method:  GET
        id: \d+
        
boxenmieten_app_component_show:
    pattern:  /komponente/{id}/{slug}
    defaults: { _controller: BoxenmietenAppBundle:Component:show }
    requirements:
        _method:  GET
        id: \d+