parameters:
#    boxenmieten_app.example.class: BoxenmietenAppBundle\Example

services:   
    boxenmieten_app.menu_builder:
        class: Boxenmieten\Bundle\AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager"]

    boxenmieten_app.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: boxenmieten_app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: bmMain }
