version: '2'
services:
  mysql:
    image: mysql:5.7.14
    environment:
      MYSQL_DATABASE: boxenmieten
      MYSQL_USER: changeThisUsername
      MYSQL_PASSWORD: changeThisPassword
      MYSQL_ROOT_PASSWORD: changeThisRootPassword
  web:
    build: .
    image: 71m024/boxenmieten
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./autodeploy:/usr/local/tomee/webapps/
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      MYSQL_USER: changeThisUsername
      MYSQL_PASSWORD: changeThisPassword
      WEB_PLATTFORM: Production


