imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @BoxenmietenAppBundle/Resources/config/config.yml }
    - { resource: @PaLogicAppBundle/Resources/config/config.yml}
    - { resource: @PaLogicUserBundle/Resources/config/config.yml}

framework:
    esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'PaLogicAppBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    read_from: "%kernel.root_dir%/../web"
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [BoxenmietenAppBundle, PaLogicBlogBundle, DjCrowdAppBundle, PaLogicAppBundle, PaLogicDjBundle, PaLogicUserBundle, DjCrowdUserBundle, FOSUserBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
                        
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            sluggable: true
    
knp_menu:
    providers:
        builder_alias: false    # disable the builder-based provider
        container_aware: true   # keep this one enabled. Can be omitted as it is the default
        
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
            
sonata_admin:
    title:      BM Admin
    
    templates:
        # default global templates
        layout:  PaLogicAdminBundle::layout.html.twig
    
sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig #keep this commented unless you are using media bundle.


        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions
            
liip_imagine:

    filter_sets:
        filter_widen:
            filters:
                relative_resize: { widen: 210 }
                
        filter_thumbnail:
            filters:
                thumbnail: { size: [270, 220], mode: outbound, allow_upscale: true }
                
        filter_portfolio_picker:
            filters:
                thumbnail: { size: [270, 220], mode: outbound, allow_upscale: true }
                
        filter_mini_thumbnail:
            filters:
                thumbnail: { size: [50, 50], mode: outbound, allow_upscale: true }
                
        filter_dj_show_banner:
            filters:
                upscale: { min: [725, 340] }
                thumbnail: { size: [725, 340], mode: outbound, allow_upscale: true }
                
        filter_dj_show_headshot:
            filters:
                upscale: { min: [500, 500] }
                thumbnail: { size: [500, 500], mode: outbound, allow_upscale: true }
                
        filter_possible_article:
            filters:
                thumbnail: { size: [400, 250], mode: outbound, allow_upscale: true }
                
        filter_component_show:
            filters:
                thumbnail: { size: [400, 400], mode: outbound, allow_upscale: true }
                
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: PaLogic\Bundle\UserBundle\Entity\PaUser
    registration:
        confirmation:
            enabled:    true
    from_email:
        address:        bot@boxenmieten.ch
        sender_name:    Boxenmieten & DJCrowd CH
        
# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_bm_transport%"
    host:        "%mailer_bm_host%"
    username:   "%mailer_bm_user%"
    password:    "%mailer_bm_password%"
    port:        "%mailer_bm_port%"
    encryption: "%mailer_bm_encryption%"
    auth_mode:  "%mailer_bm_auth_mode%"
    spool:     { type: memory }