MultipleInheritanceBundle:
    resource: .
    type: inheritance

dj_crowd_app:
    resource: "@DjCrowdAppBundle/Resources/config/routing.yml"
    prefix:   /

pa_logic_app:
    resource: "@PaLogicAppBundle/Resources/config/routing.yml"
    prefix:   /

boxenmieten_security:
    resource: "@PaLogicSecurityBundle/Resources/config/routing.yml"
    prefix:   /

boxenmieten_app:
    resource: "@BoxenmietenAppBundle/Resources/config/routing.yml"
    prefix:   /

boxenmieten_admin:
    resource: "@PaLogicAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
boxenmieten_blog:
    resource: "@BoxenmietenBlogBundle/Resources/config/routing.yml"
    prefix:   /blog
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
