MultipleInheritanceBundle:
    resource: .
    type: inheritance

dj_crowd_user:
    resource: "@DjCrowdUserBundle/Resources/config/routing.yml"
    host:     djcrowd.%tld%
    prefix:   /

dj_crowd_app:
    resource: "@DjCrowdAppBundle/Resources/config/routing.yml"
    host:     djcrowd.%tld%
    prefix:   /
    
pa_logic_blog:
    resource: "@PaLogicBlogBundle/Resources/config/routing.yml"
    host:     palogic.%tld"
    prefix:   /

boxenmieten_app:
    resource: "@BoxenmietenAppBundle/Resources/config/routing.yml"
    host:      boxenmieten.%tld%
    prefix:   /

pa_logic_app:
    resource: "@PaLogicAppBundle/Resources/config/routing.yml"
    prefix:   /

boxenmieten_admin:
    resource: "@PaLogicAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    
pa_logic_user:
    resource: "@PaLogicUserBundle/Resources/config/routing.yml"
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
