dj_crowd_app:
    resource: "@DjCrowdAppBundle/Resources/config/routing.yml"
    prefix:   /

pa_logic_app:
    resource: "@PaLogicAppBundle/Resources/config/routing.yml"
    prefix:   /

djcrowd_app:
    resource: "@DJCrowdAppBundle/Resources/config/routing.yml"
    host:     djcrowd.dev
    prefix:   /

boxenmieten_security:
    resource: "@BoxenmietenSecurityBundle/Resources/config/routing.yml"
    host:     boxenmieten.dev
    prefix:   /

boxenmieten_app:
    resource: "@BoxenmietenAppBundle/Resources/config/routing.yml"
    host:     boxenmieten.dev
    prefix:   /

boxenmieten_admin:
    resource: "@BoxenmietenAdminBundle/Resources/config/routing.yml"
    host:     boxenmieten.dev
    prefix:   /admin
    
boxenmieten_blog:
    resource: "@BoxenmietenBlogBundle/Resources/config/routing.yml"
    host:     boxenmieten.dev
    prefix:   /blog
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
