pa_logic_image:
    path:     /image
    defaults: { _controller: "PaLogicImageBundle:Image:index" }

pa_logic_image_show:
    path:     /image/{id}/show
    defaults: { _controller: "PaLogicImageBundle:Image:show" }

pa_logic_image_new:
    path:     /image/new
    defaults: { _controller: "PaLogicImageBundle:Image:new" }

pa_logic_image_create:
    path:     /image/create
    defaults: { _controller: "PaLogicImageBundle:Image:create" }
    requirements: { _method: post }

pa_logic_image_edit:
    path:     /image/{id}/edit
    defaults: { _controller: "PaLogicImageBundle:Image:edit" }

pa_logic_image_update:
    path:     /image/{id}/update
    defaults: { _controller: "PaLogicImageBundle:Image:update" }
    requirements: { _method: post|put }

pa_logic_image_delete:
    path:     /image/{id}/delete
    defaults: { _controller: "PaLogicImageBundle:Image:delete" }
    requirements: { _method: post|delete }
