parameters:
#    dj_crowd_app.example.class: DjCrowd\Bundle\AppBundle\Example

services:   
    djcrowd_app.menu_builder:
        class: DjCrowd\Bundle\AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager", "@security.context"]

    djcrowd_app.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: djcrowd_app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: dcMain }
