palogic_blog:
    pattern:  /blog
    defaults: { _controller: PaLogicBlogBundle:Blog:index}
    requirements:
        _method:  GET
        
palogic_blog_page:
    pattern:  /blog/{currentPage}
    defaults: { _controller: PaLogicBlogBundle:Blog:index}
    requirements:
        _method:  GET
        currentPage: \d+
        
palogic_blog_show:
    pattern:  /blog/{id}/{slug}
    defaults: { _controller: PaLogicBlogBundle:Blog:show}
    requirements:
        _method:  GET
        id: \d+
        
palogic_blog_comment:
    pattern:  /blog/kommentar/{post_id}
    defaults: { _controller: PaLogicBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+
        
palogic_blog_category:
    pattern:  /blog/kategorie/{categoryId}/{categoryName}
    defaults: { _controller: PaLogicBlogBundle:Category:show}
    requirements:
        _method:  GET
        categoryId: \d+

palogic_blog_category_page:
    pattern:  /blog/kategorie/{categoryId}/{categoryName}/{currentPage}
    defaults: { _controller: PaLogicBlogBundle:Category:show}
    requirements:
        _method:  GET
        currentPage: \d+
        categoryId: \d+
        
palogic_blog_tag:
    pattern:  /blog/tag/{tagId}/{tag}
    defaults: { _controller: PaLogicBlogBundle:Tag:show}
    requirements:
        _method:  GET
        tagId: \d+

palogic_blog_tag_page:
    pattern:  /blog/tag/{tagId}/{tag}/{currentPage}
    defaults: { _controller: PaLogicBlogBundle:Tag:show}
    requirements:
        _method:  GET
        currentPage: \d+
        tagId: \d+