parameters:
#    dj_crowd_blog.example.class: DjCrowd\Bundle\BlogBundle\Example

services:
#    dj_crowd_blog.example:
#        class: %dj_crowd_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
