services:   
    palogic_app.menu_builder:
        class: PaLogic\Bundle\AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager", "@security.context"]

    palogic_app.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: palogic_app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main }
            
    palogic_app.images.widget:
        class: PaLogic\Bundle\AppBundle\Form\ImagesType
        arguments: [@property_accessor]
        tags:
            - { name: form.type, alias: palogic_appbundle_images }