CREATE TABLE `ROLE` (
    ID int not null PRIMARY KEY AUTO_INCREMENT,
    NAME varchar(100) not null
);

CREATE TABLE GROUP_ROLE (
    GROUP_ID int not null,
    ROLE_ID int not null,
    PRIMARY KEY (GROUP_ID, ROLE_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES `GROUP`(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES `ROLE`(ID)
);

INSERT INTO `ROLE` (NAME)
VALUES ('EDIT_USERS'), ('EDIT_GROUPS'), ('EDIT_ROLES');

INSERT INTO GROUP_ROLE (GROUP_ID, ROLE_ID) VALUES  
(
    (SELECT ID FROM `GROUP` WHERE NAME = 'CEO'),
    (SELECT ID FROM `ROLE` WHERE NAME = 'EDIT_USERS')
),
(
    (SELECT ID FROM `GROUP` WHERE NAME = 'CEO'),
    (SELECT ID FROM `ROLE` WHERE NAME = 'EDIT_GROUPS')
),
(
    (SELECT ID FROM `GROUP` WHERE NAME = 'TechAdmin'),
    (SELECT ID FROM `ROLE` WHERE NAME = 'EDIT_ROLES')
);


