palogic_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    defaults: { _active_bundle: PaLogicUserBundle }
    prefix: /

palogic_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    defaults: { _active_bundle: PaLogicUserBundle }
    prefix: /profile

palogic_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    defaults: { _active_bundle: PaLogicUserBundle }
    prefix: /register

palogic_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    defaults: { _active_bundle: PaLogicUserBundle }
    prefix: /resetting

palogic_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    defaults: { _active_bundle: PaLogicUserBundle }
    prefix: /profile
    
palogic_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    defaults: { _active_bundle: PaLogicUserBundle }
    prefix: /group